export const countries = [
  {
    name: 'Ghana',
    icon: 'emojione:flag-for-ghana',
    code: 'GH',
    phoneCode: '+233',
  },
  {
    name: 'Afghanistan',
    icon: 'emojione:flag-for-afghanistan',
    code: 'AF',
    phoneCode: '+93',
  },
  {
    name: 'Albania',
    icon: 'emojione:flag-for-albania',
    code: 'AL',
    phoneCode: '+355',
  },
  {
    name: 'Algeria',
    icon: 'emojione:flag-for-algeria',
    code: 'DZ',
    phoneCode: '+213',
  },
  {
    name: 'Andorra',
    icon: 'emojione:flag-for-andorra',
    code: 'AD',
    phoneCode: '+376',
  },
  {
    name: 'Angola',
    icon: 'emojione:flag-for-angola',
    code: 'AO',
    phoneCode: '+244',
  },
  {
    name: 'Antigua and Barbuda',
    icon: 'emojione:flag-for-antigua-and-barbuda',
    code: 'AG',
    phoneCode: '+1-268',
  },
  {
    name: 'Argentina',
    icon: 'emojione:flag-for-argentina',
    code: 'AR',
    phoneCode: '+54',
  },
  {
    name: 'Armenia',
    icon: 'emojione:flag-for-armenia',
    code: 'AM',
    phoneCode: '+374',
  },
  {
    name: 'Australia',
    icon: 'emojione:flag-for-australia',
    code: 'AU',
    phoneCode: '+61',
  },
  {
    name: 'Austria',
    icon: 'emojione:flag-for-austria',
    code: 'AT',
    phoneCode: '+43',
  },
  {
    name: 'Azerbaijan',
    icon: 'emojione:flag-for-azerbaijan',
    code: 'AZ',
    phoneCode: '+994',
  },
  {
    name: 'Bahamas',
    icon: 'emojione:flag-for-bahamas',
    code: 'BS',
    phoneCode: '+1-242',
  },
  {
    name: 'Bahrain',
    icon: 'emojione:flag-for-bahrain',
    code: 'BH',
    phoneCode: '+973',
  },
  {
    name: 'Bangladesh',
    icon: 'emojione:flag-for-bangladesh',
    code: 'BD',
    phoneCode: '+880',
  },
  {
    name: 'Barbados',
    icon: 'emojione:flag-for-barbados',
    code: 'BB',
    phoneCode: '+1-246',
  },
  {
    name: 'Belarus',
    icon: 'emojione:flag-for-belarus',
    code: 'BY',
    phoneCode: '+375',
  },
  {
    name: 'Belgium',
    icon: 'emojione:flag-for-belgium',
    code: 'BE',
    phoneCode: '+32',
  },
  {
    name: 'Belize',
    icon: 'emojione:flag-for-belize',
    code: 'BZ',
    phoneCode: '+501',
  },
  {
    name: 'Benin',
    icon: 'emojione:flag-for-benin',
    code: 'BJ',
    phoneCode: '+229',
  },
  {
    name: 'Bhutan',
    icon: 'emojione:flag-for-bhutan',
    code: 'BT',
    phoneCode: '+975',
  },
  {
    name: 'Bolivia',
    icon: 'emojione:flag-for-bolivia',
    code: 'BO',
    phoneCode: '+591',
  },
  {
    name: 'Bosnia and Herzegovina',
    icon: 'emojione:flag-for-bosnia-and-herzegovina',
    code: 'BA',
    phoneCode: '+387',
  },
  {
    name: 'Botswana',
    icon: 'emojione:flag-for-botswana',
    code: 'BW',
    phoneCode: '+267',
  },
  {
    name: 'Brunei',
    icon: 'emojione:flag-for-brunei',
    code: 'BN',
    phoneCode: '+673',
  },
  {
    name: 'Bulgaria',
    icon: 'emojione:flag-for-bulgaria',
    code: 'BG',
    phoneCode: '+359',
  },
  {
    name: 'Burkina Faso',
    icon: 'emojione:flag-for-burkina-faso',
    code: 'BF',
    phoneCode: '+226',
  },
  {
    name: 'Burundi',
    icon: 'emojione:flag-for-burundi',
    code: 'BI',
    phoneCode: '+257',
  },
  {
    name: 'Cape Verde',
    icon: 'emojione:flag-for-cape-verde',
    code: 'CV',
    phoneCode: '+238',
  },
  {
    name: 'Cambodia',
    icon: 'emojione:flag-for-cambodia',
    code: 'KH',
    phoneCode: '+855',
  },
  {
    name: 'Cameroon',
    icon: 'emojione:flag-for-cameroon',
    code: 'CM',
    phoneCode: '+237',
  },
  {
    name: 'Canada',
    icon: 'emojione:flag-for-canada',
    code: 'CA',
    phoneCode: '+1',
  },
  {
    name: 'Central African Republic',
    icon: 'emojione:flag-for-central-african-republic',
    code: 'CF',
    phoneCode: '+236',
  },
  {
    name: 'Chad',
    icon: 'emojione:flag-for-chad',
    code: 'TD',
    phoneCode: '+235',
  },
  {
    name: 'Chile',
    icon: 'emojione:flag-for-chile',
    code: 'CL',
    phoneCode: '+56',
  },
  {
    name: 'China',
    icon: 'emojione:flag-for-china',
    code: 'CN',
    phoneCode: '+86',
  },
  {
    name: 'Colombia',
    icon: 'emojione:flag-for-colombia',
    code: 'CO',
    phoneCode: '+57',
  },
  {
    name: 'Comoros',
    icon: 'emojione:flag-for-comoros',
    code: 'KM',
    phoneCode: '+269',
  },
  {
    name: 'Congo (Congo-Brazzaville)',
    icon: 'emojione:flag-for-congo-brazzaville',
    code: 'CG',
    phoneCode: '+242',
  },
  {
    name: 'Congo (Congo-Kinshasa)',
    icon: 'emojione:flag-for-congo-kinshasa',
    code: 'CD',
    phoneCode: '+243',
  },
  {
    name: 'Costa Rica',
    icon: 'emojione:flag-for-costa-rica',
    code: 'CR',
    phoneCode: '+506',
  },
  {
    name: 'Croatia',
    icon: 'emojione:flag-for-croatia',
    code: 'HR',
    phoneCode: '+385',
  },
  {
    name: 'Cuba',
    icon: 'emojione:flag-for-cuba',
    code: 'CU',
    phoneCode: '+53',
  },
  {
    name: 'Cyprus',
    icon: 'emojione:flag-for-cyprus',
    code: 'CY',
    phoneCode: '+357',
  },
  {
    name: 'Czechia',
    icon: 'emojione:flag-for-czechia',
    code: 'CZ',
    phoneCode: '+420',
  },
  {
    name: 'Denmark',
    icon: 'emojione:flag-for-denmark',
    code: 'DK',
    phoneCode: '+45',
  },
  {
    name: 'Djibouti',
    icon: 'emojione:flag-for-djibouti',
    code: 'DJ',
    phoneCode: '+253',
  },
  {
    name: 'Dominica',
    icon: 'emojione:flag-for-dominica',
    code: 'DM',
    phoneCode: '+1-767',
  },
  {
    name: 'Dominican Republic',
    icon: 'emojione:flag-for-dominican-republic',
    code: 'DO',
    phoneCode: '+1-809',
  },
  {
    name: 'Ecuador',
    icon: 'emojione:flag-for-ecuador',
    code: 'EC',
    phoneCode: '+593',
  },
  {
    name: 'Egypt',
    icon: 'emojione:flag-for-egypt',
    code: 'EG',
    phoneCode: '+20',
  },
  {
    name: 'El Salvador',
    icon: 'emojione:flag-for-el-salvador',
    code: 'SV',
    phoneCode: '+503',
  },
  {
    name: 'Equatorial Guinea',
    icon: 'emojione:flag-for-equatorial-guinea',
    code: 'GQ',
    phoneCode: '+240',
  },
  {
    name: 'Eritrea',
    icon: 'emojione:flag-for-eritrea',
    code: 'ER',
    phoneCode: '+291',
  },
  {
    name: 'Estonia',
    icon: 'emojione:flag-for-estonia',
    code: 'EE',
    phoneCode: '+372',
  },
  {
    name: 'Eswatini',
    icon: 'emojione:flag-for-flag-eswatini',
    code: 'SZ',
    phoneCode: '+268',
  },
  {
    name: 'Ethiopia',
    icon: 'emojione:flag-for-ethiopia',
    code: 'ET',
    phoneCode: '+251',
  },
  {
    name: 'Fiji',
    icon: 'emojione:flag-for-fiji',
    code: 'FJ',
    phoneCode: '+679',
  },
  {
    name: 'Finland',
    icon: 'emojione:flag-for-finland',
    code: 'FI',
    phoneCode: '+358',
  },
  {
    name: 'France',
    icon: 'emojione:flag-for-france',
    code: 'FR',
    phoneCode: '+33',
  },
  {
    name: 'Gabon',
    icon: 'emojione:flag-for-gabon',
    code: 'GA',
    phoneCode: '+241',
  },
  {
    name: 'Gambia',
    icon: 'emojione:flag-for-gambia',
    code: 'GM',
    phoneCode: '+220',
  },
  {
    name: 'Georgia',
    icon: 'emojione:flag-for-georgia',
    code: 'GE',
    phoneCode: '+995',
  },
  {
    name: 'Germany',
    icon: 'emojione:flag-for-germany',
    code: 'DE',
    phoneCode: '+49',
  },
  {
    name: 'Greece',
    icon: 'emojione:flag-for-greece',
    code: 'GR',
    phoneCode: '+30',
  },
  {
    name: 'Grenada',
    icon: 'emojione:flag-for-grenada',
    code: 'GD',
    phoneCode: '+1-473',
  },
  {
    name: 'Guatemala',
    icon: 'emojione:flag-for-guatemala',
    code: 'GT',
    phoneCode: '+502',
  },
  {
    name: 'Guinea',
    icon: 'emojione:flag-for-guinea',
    code: 'GN',
    phoneCode: '+224',
  },
  {
    name: 'Guinea-Bissau',
    icon: 'emojione:flag-for-guinea-bissau',
    code: 'GW',
    phoneCode: '+245',
  },
  {
    name: 'Guyana',
    icon: 'emojione:flag-for-guyana',
    code: 'GY',
    phoneCode: '+592',
  },
  {
    name: 'Haiti',
    icon: 'emojione:flag-for-haiti',
    code: 'HT',
    phoneCode: '+509',
  },
  {
    name: 'Honduras',
    icon: 'emojione:flag-for-honduras',
    code: 'HN',
    phoneCode: '+504',
  },
  {
    name: 'Hungary',
    icon: 'emojione:flag-for-hungary',
    code: 'HU',
    phoneCode: '+36',
  },
  {
    name: 'Iceland',
    icon: 'emojione:flag-for-iceland',
    code: 'IS',
    phoneCode: '+354',
  },
  {
    name: 'India',
    icon: 'emojione:flag-for-india',
    code: 'IN',
    phoneCode: '+91',
  },
  {
    name: 'Indonesia',
    icon: 'emojione:flag-for-indonesia',
    code: 'ID',
    phoneCode: '+62',
  },
  {
    name: 'Iran',
    icon: 'emojione:flag-for-iran',
    code: 'IR',
    phoneCode: '+98',
  },
  {
    name: 'Iraq',
    icon: 'emojione:flag-for-iraq',
    code: 'IQ',
    phoneCode: '+964',
  },
  {
    name: 'Ireland',
    icon: 'emojione:flag-for-ireland',
    code: 'IE',
    phoneCode: '+353',
  },
  {
    name: 'Israel',
    icon: 'emojione:flag-for-israel',
    code: 'IL',
    phoneCode: '+972',
  },
  {
    name: 'Italy',
    icon: 'emojione:flag-for-italy',
    code: 'IT',
    phoneCode: '+39',
  },
  {
    name: 'Jamaica',
    icon: 'emojione:flag-for-jamaica',
    code: 'JM',
    phoneCode: '+1-876',
  },
  {
    name: 'Japan',
    icon: 'emojione:flag-for-japan',
    code: 'JP',
    phoneCode: '+81',
  },
  {
    name: 'Jordan',
    icon: 'emojione:flag-for-jordan',
    code: 'JO',
    phoneCode: '+962',
  },
  {
    name: 'Kazakhstan',
    icon: 'emojione:flag-for-kazakhstan',
    code: 'KZ',
    phoneCode: '+7',
  },
  {
    name: 'Kenya',
    icon: 'emojione:flag-for-kenya',
    code: 'KE',
    phoneCode: '+254',
  },
  {
    name: 'Kiribati',
    icon: 'emojione:flag-for-kiribati',
    code: 'KI',
    phoneCode: '+686',
  },
  {
    name: 'Korea (North)',
    icon: 'emojione:flag-for-korea-north',
    code: 'KP',
    phoneCode: '+850',
  },
  {
    name: 'Korea (South)',
    icon: 'emojione:flag-for-korea-south',
    code: 'KR',
    phoneCode: '+82',
  },
  {
    name: 'Kuwait',
    icon: 'emojione:flag-for-kuwait',
    code: 'KW',
    phoneCode: '+965',
  },
  {
    name: 'Kyrgyzstan',
    icon: 'emojione:flag-for-kyrgyzstan',
    code: 'KG',
    phoneCode: '+996',
  },
  {
    name: 'Laos',
    icon: 'emojione:flag-for-laos',
    code: 'LA',
    phoneCode: '+856',
  },
  {
    name: 'Latvia',
    icon: 'emojione:flag-for-latvia',
    code: 'LV',
    phoneCode: '+371',
  },
  {
    name: 'Lebanon',
    icon: 'emojione:flag-for-lebanon',
    code: 'LB',
    phoneCode: '+961',
  },
  {
    name: 'Lesotho',
    icon: 'emojione:flag-for-lesotho',
    code: 'LS',
    phoneCode: '+266',
  },
  {
    name: 'Liberia',
    icon: 'emojione:flag-for-liberia',
    code: 'LR',
    phoneCode: '+231',
  },
  {
    name: 'Libya',
    icon: 'emojione:flag-for-libya',
    code: 'LY',
    phoneCode: '+218',
  },
  {
    name: 'Liechtenstein',
    icon: 'emojione:flag-for-liechtenstein',
    code: 'LI',
    phoneCode: '+423',
  },
  {
    name: 'Lithuania',
    icon: 'emojione:flag-for-lithuania',
    code: 'LT',
    phoneCode: '+370',
  },
  {
    name: 'Luxembourg',
    icon: 'emojione:flag-for-luxembourg',
    code: 'LU',
    phoneCode: '+352',
  },
  {
    name: 'Madagascar',
    icon: 'emojione:flag-for-madagascar',
    code: 'MG',
    phoneCode: '+261',
  },
  {
    name: 'Malawi',
    icon: 'emojione:flag-for-malawi',
    code: 'MW',
    phoneCode: '+265',
  },
  {
    name: 'Malaysia',
    icon: 'emojione:flag-for-malaysia',
    code: 'MY',
    phoneCode: '+60',
  },
  {
    name: 'Maldives',
    icon: 'emojione:flag-for-maldives',
    code: 'MV',
    phoneCode: '+960',
  },
  {
    name: 'Mali',
    icon: 'emojione:flag-for-mali',
    code: 'ML',
    phoneCode: '+223',
  },
  {
    name: 'Malta',
    icon: 'emojione:flag-for-malta',
    code: 'MT',
    phoneCode: '+356',
  },
  {
    name: 'Marshall Islands',
    icon: 'emojione:flag-for-marshall-islands',
    code: 'MH',
    phoneCode: '+692',
  },
  {
    name: 'Mauritania',
    icon: 'emojione:flag-for-mauritania',
    code: 'MR',
    phoneCode: '+222',
  },
  {
    name: 'Mauritius',
    icon: 'emojione:flag-for-mauritius',
    code: 'MU',
    phoneCode: '+230',
  },
  {
    name: 'Mexico',
    icon: 'emojione:flag-for-mexico',
    code: 'MX',
    phoneCode: '+52',
  },
  {
    name: 'Micronesia',
    icon: 'emojione:flag-for-micronesia',
    code: 'FM',
    phoneCode: '+691',
  },
  {
    name: 'Moldova',
    icon: 'emojione:flag-for-moldova',
    code: 'MD',
    phoneCode: '+373',
  },
  {
    name: 'Monaco',
    icon: 'emojione:flag-for-monaco',
    code: 'MC',
    phoneCode: '+377',
  },
  {
    name: 'Mongolia',
    icon: 'emojione:flag-for-mongolia',
    code: 'MN',
    phoneCode: '+976',
  },
  {
    name: 'Montenegro',
    icon: 'emojione:flag-for-montenegro',
    code: 'ME',
    phoneCode: '+382',
  },
  {
    name: 'Morocco',
    icon: 'emojione:flag-for-morocco',
    code: 'MA',
    phoneCode: '+212',
  },
  {
    name: 'Mozambique',
    icon: 'emojione:flag-for-mozambique',
    code: 'MZ',
    phoneCode: '+258',
  },
  {
    name: 'Myanmar (Burma)',
    icon: 'emojione:flag-for-myanmar',
    code: 'MM',
    phoneCode: '+95',
  },
  {
    name: 'Namibia',
    icon: 'emojione:flag-for-namibia',
    code: 'NA',
    phoneCode: '+264',
  },
  {
    name: 'Nauru',
    icon: 'emojione:flag-for-nauru',
    code: 'NR',
    phoneCode: '+674',
  },
  {
    name: 'Nepal',
    icon: 'emojione:flag-for-nepal',
    code: 'NP',
    phoneCode: '+977',
  },
  {
    name: 'Netherlands',
    icon: 'emojione:flag-for-netherlands',
    code: 'NL',
    phoneCode: '+31',
  },
  {
    name: 'New Zealand',
    icon: 'emojione:flag-for-new-zealand',
    code: 'NZ',
    phoneCode: '+64',
  },
  {
    name: 'Nicaragua',
    icon: 'emojione:flag-for-nicaragua',
    code: 'NI',
    phoneCode: '+505',
  },
  {
    name: 'Niger',
    icon: 'emojione:flag-for-niger',
    code: 'NE',
    phoneCode: '+227',
  },
  {
    name: 'Nigeria',
    icon: 'emojione:flag-for-nigeria',
    code: 'NG',
    phoneCode: '+234',
  },
  {
    name: 'North Macedonia',
    icon: 'emojione:flag-for-north-macedonia',
    code: 'MK',
    phoneCode: '+389',
  },
  {
    name: 'Norway',
    icon: 'emojione:flag-for-norway',
    code: 'NO',
    phoneCode: '+47',
  },
  {
    name: 'Oman',
    icon: 'emojione:flag-for-oman',
    code: 'OM',
    phoneCode: '+968',
  },
  {
    name: 'Pakistan',
    icon: 'emojione:flag-for-pakistan',
    code: 'PK',
    phoneCode: '+92',
  },
  {
    name: 'Palau',
    icon: 'emojione:flag-for-palau',
    code: 'PW',
    phoneCode: '+680',
  },
  {
    name: 'Panama',
    icon: 'emojione:flag-for-panama',
    code: 'PA',
    phoneCode: '+507',
  },
  {
    name: 'Papua New Guinea',
    icon: 'emojione:flag-for-papua-new-guinea',
    code: 'PG',
    phoneCode: '+675',
  },
  {
    name: 'Paraguay',
    icon: 'emojione:flag-for-paraguay',
    code: 'PY',
    phoneCode: '+595',
  },
  {
    name: 'Peru',
    icon: 'emojione:flag-for-peru',
    code: 'PE',
    phoneCode: '+51',
  },
  {
    name: 'Philippines',
    icon: 'emojione:flag-for-philippines',
    code: 'PH',
    phoneCode: '+63',
  },
  {
    name: 'Poland',
    icon: 'emojione:flag-for-poland',
    code: 'PL',
    phoneCode: '+48',
  },
  {
    name: 'Portugal',
    icon: 'emojione:flag-for-portugal',
    code: 'PT',
    phoneCode: '+351',
  },
  {
    name: 'Qatar',
    icon: 'emojione:flag-for-qatar',
    code: 'QA',
    phoneCode: '+974',
  },
  {
    name: 'Romania',
    icon: 'emojione:flag-for-romania',
    code: 'RO',
    phoneCode: '+40',
  },
  {
    name: 'Russia',
    icon: 'emojione:flag-for-russia',
    code: 'RU',
    phoneCode: '+7',
  },
  {
    name: 'Rwanda',
    icon: 'emojione:flag-for-rwanda',
    code: 'RW',
    phoneCode: '+250',
  },
  {
    name: 'Saint Kitts and Nevis',
    icon: 'emojione:flag-for-saint-kitts-and-nevis',
    code: 'KN',
    phoneCode: '+1-869',
  },
  {
    name: 'Saint Lucia',
    icon: 'emojione:flag-for-saint-lucia',
    code: 'LC',
    phoneCode: '+1-758',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    icon: 'emojione:flag-for-saint-vincent-and-the-grenadines',
    code: 'VC',
    phoneCode: '+1-784',
  },
  {
    name: 'Samoa',
    icon: 'emojione:flag-for-samoa',
    code: 'WS',
    phoneCode: '+685',
  },
  {
    name: 'San Marino',
    icon: 'emojione:flag-for-san-marino',
    code: 'SM',
    phoneCode: '+378',
  },
  {
    name: 'Sao Tome and Principe',
    icon: 'emojione:flag-for-sao-tome-and-principe',
    code: 'ST',
    phoneCode: '+239',
  },
  {
    name: 'Saudi Arabia',
    icon: 'emojione:flag-for-saudi-arabia',
    code: 'SA',
    phoneCode: '+966',
  },
  {
    name: 'Senegal',
    icon: 'emojione:flag-for-senegal',
    code: 'SN',
    phoneCode: '+221',
  },
  {
    name: 'Serbia',
    icon: 'emojione:flag-for-serbia',
    code: 'RS',
    phoneCode: '+381',
  },
  {
    name: 'Seychelles',
    icon: 'emojione:flag-for-seychelles',
    code: 'SC',
    phoneCode: '+248',
  },
  {
    name: 'Sierra Leone',
    icon: 'emojione:flag-for-sierra-leone',
    code: 'SL',
    phoneCode: '+232',
  },
  {
    name: 'Singapore',
    icon: 'emojione:flag-for-singapore',
    code: 'SG',
    phoneCode: '+65',
  },
  {
    name: 'Slovakia',
    icon: 'emojione:flag-for-slovakia',
    code: 'SK',
    phoneCode: '+421',
  },
  {
    name: 'Slovenia',
    icon: 'emojione:flag-for-slovenia',
    code: 'SI',
    phoneCode: '+386',
  },
  {
    name: 'Solomon Islands',
    icon: 'emojione:flag-for-solomon-islands',
    code: 'SB',
    phoneCode: '+677',
  },
  {
    name: 'Somalia',
    icon: 'emojione:flag-for-somalia',
    code: 'SO',
    phoneCode: '+252',
  },
  {
    name: 'South Africa',
    icon: 'emojione:flag-for-south-africa',
    code: 'ZA',
    phoneCode: '+27',
  },
  {
    name: 'South Sudan',
    icon: 'emojione:flag-for-south-sudan',
    code: 'SS',
    phoneCode: '+211',
  },
  {
    name: 'Spain',
    icon: 'emojione:flag-for-spain',
    code: 'ES',
    phoneCode: '+34',
  },
  {
    name: 'Sri Lanka',
    icon: 'emojione:flag-for-sri-lanka',
    code: 'LK',
    phoneCode: '+94',
  },
  {
    name: 'Sudan',
    icon: 'emojione:flag-for-sudan',
    code: 'SD',
    phoneCode: '+249',
  },
  {
    name: 'Suriname',
    icon: 'emojione:flag-for-suriname',
    code: 'SR',
    phoneCode: '+597',
  },
  {
    name: 'Sweden',
    icon: 'emojione:flag-for-sweden',
    code: 'SE',
    phoneCode: '+46',
  },
  {
    name: 'Switzerland',
    icon: 'emojione:flag-for-switzerland',
    code: 'CH',
    phoneCode: '+41',
  },
  {
    name: 'Syria',
    icon: 'emojione:flag-for-syria',
    code: 'SY',
    phoneCode: '+963',
  },
  {
    name: 'Taiwan',
    icon: 'emojione:flag-for-taiwan',
    code: 'TW',
    phoneCode: '+886',
  },
  {
    name: 'Tajikistan',
    icon: 'emojione:flag-for-tajikistan',
    code: 'TJ',
    phoneCode: '+992',
  },
  {
    name: 'Tanzania',
    icon: 'emojione:flag-for-tanzania',
    code: 'TZ',
    phoneCode: '+255',
  },
  {
    name: 'Thailand',
    icon: 'emojione:flag-for-thailand',
    code: 'TH',
    phoneCode: '+66',
  },
  {
    name: 'Togo',
    icon: 'emojione:flag-for-togo',
    code: 'TG',
    phoneCode: '+228',
  },
  {
    name: 'Tonga',
    icon: 'emojione:flag-for-tonga',
    code: 'TO',
    phoneCode: '+676',
  },
  {
    name: 'Trinidad and Tobago',
    icon: 'emojione:flag-for-trinidad-and-tobago',
    code: 'TT',
    phoneCode: '+1-868',
  },
  {
    name: 'Tunisia',
    icon: 'emojione:flag-for-tunisia',
    code: 'TN',
    phoneCode: '+216',
  },
  {
    name: 'Turkey',
    icon: 'emojione:flag-for-turkey',
    code: 'TR',
    phoneCode: '+90',
  },
  {
    name: 'Turkmenistan',
    icon: 'emojione:flag-for-turkmenistan',
    code: 'TM',
    phoneCode: '+993',
  },
  {
    name: 'Tuvalu',
    icon: 'emojione:flag-for-tuvalu',
    code: 'TV',
    phoneCode: '+688',
  },
  {
    name: 'Uganda',
    icon: 'emojione:flag-for-uganda',
    code: 'UG',
    phoneCode: '+256',
  },
  {
    name: 'Ukraine',
    icon: 'emojione:flag-for-ukraine',
    code: 'UA',
    phoneCode: '+380',
  },
  {
    name: 'United Arab Emirates',
    icon: 'emojione:flag-for-united-arab-emirates',
    code: 'AE',
    phoneCode: '+971',
  },
  {
    name: 'United Kingdom',
    icon: 'emojione:flag-for-united-kingdom',
    code: 'GB',
    phoneCode: '+44',
  },
  {
    name: 'United States',
    icon: 'emojione:flag-for-united-states',
    code: 'US',
    phoneCode: '+1',
  },
  {
    name: 'Uruguay',
    icon: 'emojione:flag-for-uruguay',
    code: 'UY',
    phoneCode: '+598',
  },
  {
    name: 'Uzbekistan',
    icon: 'emojione:flag-for-uzbekistan',
    code: 'UZ',
    phoneCode: '+998',
  },
  {
    name: 'Vanuatu',
    icon: 'emojione:flag-for-vanuatu',
    code: 'VU',
    phoneCode: '+678',
  },
  {
    name: 'Vatican City',
    icon: 'emojione:flag-for-vatican-city',
    code: 'VA',
    phoneCode: '+379',
  },
  {
    name: 'Venezuela',
    icon: 'emojione:flag-for-venezuela',
    code: 'VE',
    phoneCode: '+58',
  },
  {
    name: 'Vietnam',
    icon: 'emojione:flag-for-vietnam',
    code: 'VN',
    phoneCode: '+84',
  },
  {
    name: 'Yemen',
    icon: 'emojione:flag-for-yemen',
    code: 'YE',
    phoneCode: '+967',
  },
  {
    name: 'Zambia',
    icon: 'emojione:flag-for-zambia',
    code: 'ZM',
    phoneCode: '+260',
  },
  {
    name: 'Zimbabwe',
    icon: 'emojione:flag-for-zimbabwe',
    code: 'ZW',
    phoneCode: '+263',
  },
  {
    name: 'Palestine',
    icon: 'emojione:flag-for-palestinian-territories',
    code: 'PS',
    phoneCode: '+970',
  },
  {
    name: 'India',
    icon: 'emojione:flag-for-india',
    code: 'IN',
    phoneCode: '+91',
  },
  {
    name: 'Japan',
    icon: 'emojione:flag-for-japan',
    code: 'JP',
    phoneCode: '+81',
  },
  {
    name: 'Brazil',
    icon: 'emojione:flag-for-brazil',
    code: 'BR',
    phoneCode: '+55',
  },
  {
    name: 'South Africa',
    icon: 'emojione:flag-for-south-africa',
    code: 'ZA',
    phoneCode: '+27',
  },
  {
    name: 'Australia',
    icon: 'emojione:flag-for-australia',
    code: 'AU',
    phoneCode: '+61',
  },
  {
    name: 'Russia',
    icon: 'emojione:flag-for-russia',
    code: 'RU',
    phoneCode: '+7',
  },
  {
    name: 'China',
    icon: 'emojione:flag-for-china',
    code: 'CN',
    phoneCode: '+86',
  },
  {
    name: 'Iran',
    icon: 'emojione:flag-for-iran',
    code: 'IR',
    phoneCode: '+98',
  },
  {
    name: 'Turkey',
    icon: 'emojione:flag-for-turkey',
    code: 'TR',
    phoneCode: '+90',
  },
  {
    name: 'Germany',
    icon: 'emojione:flag-for-germany',
    code: 'DE',
    phoneCode: '+49',
  },
  {
    name: 'United Kingdom',
    icon: 'emojione:flag-for-united-kingdom',
    code: 'GB',
    phoneCode: '+44',
  },
  {
    name: 'Italy',
    icon: 'emojione:flag-for-italy',
    code: 'IT',
    phoneCode: '+39',
  },
  {
    name: 'Spain',
    icon: 'emojione:flag-for-spain',
    code: 'ES',
    phoneCode: '+34',
  },
  {
    name: 'Mexico',
    icon: 'emojione:flag-for-mexico',
    code: 'MX',
    phoneCode: '+52',
  },
  {
    name: 'Nigeria',
    icon: 'emojione:flag-for-nigeria',
    code: 'NG',
    phoneCode: '+234',
  },
];
